CREATE TABLE Department (
  DNO NUMBER(*,0) CONSTRAINT DEPARTMENT_PK PRIMARY KEY,
  DNAME VARCHAR2(30) CONSTRAINT DEPARTMENT_DNAME_UN NOT NULL,
  DLOCATION VARCHAR2(30) CONSTRAINT DEPARTMENT_DLOCATION_UN NOT NULL
);

CREATE TABLE Employee (
  ENO CHAR(4) CONSTRAINT EMPLOYEE_PK PRIMARY KEY,
  ENAME VARCHAR2(30) NOT NULL,
  JOB VARCHAR2(30) NOT NULL,
  MANAGER CHAR(4),
  JDATE TIMESTAMP NOT NULL,
  GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
  SALARY NUMBER(8, 2) CHECK (SALARY > 0),
  COMMISSION NUMBER(8, 2) DEFAULT 0,
  DEPTNO NUMBER(*,0) CONSTRAINT EMPLOYEE_DEPT_FK NOT NULL
);

INSERT INTO Department (DNO, DNAME, DLOCATION)
VALUES (10, 'Sales', 'Missisauga');

INSERT INTO Department (DNO, DNAME, DLOCATION)
VALUES (20, 'Marketing', 'Toronto');

INSERT INTO Department (DNO, DNAME, DLOCATION)
VALUES (30, 'Human Resources', 'Vaughan');

INSERT INTO Department (DNO, DNAME, DLOCATION)
VALUES (40, 'Engineering', 'Montreal');

INSERT INTO Department (DNO, DNAME, DLOCATION)
VALUES (50, 'IT', 'Calgary');


INSERT INTO Employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO)
VALUES ('E001', 'John Doe', 'Sales Representative', 'Eri', '04-apr-24 10:30:40', 'M', 80000.00, 5000.00, 10);

INSERT INTO Employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO)
VALUES ('E002', 'Jane Smith', 'Marketing Manager', 'Lynn', '19-jun-24 08:45:40', 'F', 100000.00, 7000.00, 20);

INSERT INTO Employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO)
VALUES ('E03', 'Lennon Dalton', 'Data Analyst', 'Ale', '30-aug-24 05:30:40', 'M', 5000.00, 4000.00, 10);

INSERT INTO Employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO)
VALUES ('E04', 'Caitlyn Thompson', 'Business Analyst', 'Hane', '13-jan-24 02:13:40', 'F', 40000.00, 9000.00, 30);

INSERT INTO Employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO)
VALUES ('E05', 'Harmony Conner', 'Risky Manager', 'Kauf', '28-may-24 09:20:40', 'M', 50000.00, 2500.00, 40);






