-- Create table
CREATE TABLE comm_product_color (
    color_id INT PRIMARY KEY,  
    color_name VARCHAR(255)NOT NULL,
    product_image VARCHAR(255)
);
CREATE TABLE comm_product_size (
	size_id INT PRIMARY KEY,  
    size_description VARCHAR(255)NOT NULL
);
CREATE TABLE comm_product_category (
	category_id INT PRIMARY KEY,
    category_name VARCHAR(255)NOT NULL
);
CREATE TABLE comm_product_brand (
	brand_id INT PRIMARY KEY,
    brand_name VARCHAR(255)NOT NULL
);
CREATE TABLE comm_customer (
	customer_id INT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    street VARCHAR(255)NOT NULL,
    zip_code VARCHAR(255) NOT NULL,
    province VARCHAR(255) NOT NULL
);
CREATE TABLE comm_product (
	product_id INT PRIMARY KEY,
    product_name VARCHAR(255),
    brand_id INT NOT NULL,
    color_id INT NOT NULL,
    size_id INT NOT NULL,
    category_id INT NOT NULL,
    product_price DECIMAL(10,2),
    FOREIGN KEY (brand_id) REFERENCES comm_product_brand(brand_id),
    FOREIGN KEY (color_id) REFERENCES comm_product_color(color_id),
    FOREIGN KEY (size_id) REFERENCES comm_product_size(size_id),
    FOREIGN KEY (category_id) REFERENCES comm_product_category(category_id)   
);
CREATE TABLE comm_payment (
    payment_id INT PRIMARY KEY,
    customer_id INT,
    payment_date DATE,
    payment_method VARCHAR(255)NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES comm_customer(customer_id)
);
CREATE TABLE comm_shipping (
	shipping_id INT PRIMARY KEY,    
    shipped_date DATE,
    customer_id INT,
    status INT NOT NULL,
--    (1:processing, 2:rejected, 3:shipped)
    FOREIGN KEY (customer_id) REFERENCES comm_customer(customer_id)
);
CREATE TABLE comm_shopping_cart (
    cart_id INT PRIMARY KEY,
    customer_id INT,
    product_id INT,
    quantity INT,
    FOREIGN KEY (customer_id) REFERENCES comm_customer(customer_id),
    FOREIGN KEY ( product_id) REFERENCES comm_product(product_id)
);
CREATE TABLE comm_order (
    order_id INT PRIMARY KEY,
    customer_id INT,
    payment_id INT,
    shipping_id INT,
    order_date DATE,
    total_price DECIMAL(10,2),
    FOREIGN KEY (customer_id) REFERENCES comm_customer(customer_id),
    FOREIGN KEY (payment_id) REFERENCES comm_payment(payment_id),
    FOREIGN KEY (shipping_id) REFERENCES comm_shipping(shipping_id)
);
CREATE TABLE comm_order_item (    
    order_item_id INT,
    quantity INT,	
    price DECIMAL(10,2),
    product_id INT,
    order_id INT,
    PRIMARY KEY(order_item_id,order_id),
    FOREIGN KEY ( product_id) REFERENCES comm_product(product_id),
    FOREIGN KEY ( order_id) REFERENCES comm_order(order_id)
);

-- Insert records
INSERT ALL
    INTO COMM_CUSTOMER(CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,STREET,ZIP_CODE,PROVINCE) VALUES(1,'John','Block','bjohn@gmail.com','437-222-5623','Ossington Ave','M3G 6T7','ON')
    INTO COMM_CUSTOMER(CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,STREET,ZIP_CODE,PROVINCE) VALUES(2,'Diana','Smith','sdiana@gmail.com','437-888-7777','St.George Ave','O3N 6T7','BC')
    INTO COMM_CUSTOMER(CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,STREET,ZIP_CODE,PROVINCE) VALUES(3,'John','Block','bjohn@gmail.com','437-222-5623','Ossington Ave','T6H 6T7','ON')
    INTO COMM_CUSTOMER(CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,STREET,ZIP_CODE,PROVINCE) VALUES(4,'John','Block','bjohn@gmail.com','437-222-5623','Ossington Ave','M3G F5G','BC')
    INTO COMM_CUSTOMER(CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,STREET,ZIP_CODE,PROVINCE) VALUES(5,'John','Block','bjohn@gmail.com','437-222-5623','Ossington Ave','U3G 6T7','ON')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COMM_PRODUCT_BRAND(BRAND_ID,BRAND_NAME) VALUES(100001,'HM')
    INTO COMM_PRODUCT_BRAND(BRAND_ID,BRAND_NAME) VALUES(100002,'Tommy')
    INTO COMM_PRODUCT_BRAND(BRAND_ID,BRAND_NAME) VALUES(100003,'Caribbean')
    INTO COMM_PRODUCT_BRAND(BRAND_ID,BRAND_NAME) VALUES(100004,'Emy')
    INTO COMM_PRODUCT_BRAND(BRAND_ID,BRAND_NAME) VALUES(100005,'Channel')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COMM_PRODUCT_CATEGORY(CATEGORY_ID,CATEGORY_NAME) VALUES(101,'T-shirt')
    INTO COMM_PRODUCT_CATEGORY(CATEGORY_ID,CATEGORY_NAME) VALUES(102,'Skirt')
    INTO COMM_PRODUCT_CATEGORY(CATEGORY_ID,CATEGORY_NAME) VALUES(103,'Short')
    INTO COMM_PRODUCT_CATEGORY(CATEGORY_ID,CATEGORY_NAME) VALUES(104,'Coat')
    INTO COMM_PRODUCT_CATEGORY(CATEGORY_ID,CATEGORY_NAME) VALUES(105,'Pants')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COMM_PRODUCT_COLOR(COLOR_ID,COLOR_NAME,PRODUCT_IMAGE) VALUES(1001,'Red','')
    INTO COMM_PRODUCT_COLOR(COLOR_ID,COLOR_NAME,PRODUCT_IMAGE) VALUES(1002,'Blue','')
    INTO COMM_PRODUCT_COLOR(COLOR_ID,COLOR_NAME,PRODUCT_IMAGE) VALUES(1003,'Green','')
    INTO COMM_PRODUCT_COLOR(COLOR_ID,COLOR_NAME,PRODUCT_IMAGE) VALUES(1004,'Black','')
    INTO COMM_PRODUCT_COLOR(COLOR_ID,COLOR_NAME,PRODUCT_IMAGE) VALUES(1005,'White','')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COMM_PRODUCT_SIZE(SIZE_ID,SIZE_DESCRIPTION) VALUES(101,'extra small')
    INTO COMM_PRODUCT_SIZE(SIZE_ID,SIZE_DESCRIPTION) VALUES(102,'small')
    INTO COMM_PRODUCT_SIZE(SIZE_ID,SIZE_DESCRIPTION) VALUES(103,'medium')
    INTO COMM_PRODUCT_SIZE(SIZE_ID,SIZE_DESCRIPTION) VALUES(104,'large')
    INTO COMM_PRODUCT_SIZE(SIZE_ID,SIZE_DESCRIPTION) VALUES(105,'extra large')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COMM_PRODUCT(PRODUCT_ID,PRODUCT_NAME,BRAND_ID,COLOR_ID,SIZE_ID,CATEGORY_ID,PRODUCT_PRICE) VALUES(101,'long sleeve t-shirt',100001,1001,101,101,20)
    INTO COMM_PRODUCT(PRODUCT_ID,PRODUCT_NAME,BRAND_ID,COLOR_ID,SIZE_ID,CATEGORY_ID,PRODUCT_PRICE) VALUES(102,'long skirt',100002,1002,102,102,13)
    INTO COMM_PRODUCT(PRODUCT_ID,PRODUCT_NAME,BRAND_ID,COLOR_ID,SIZE_ID,CATEGORY_ID,PRODUCT_PRICE) VALUES(103,'shorts',100003,1003,103,103,22)
    INTO COMM_PRODUCT(PRODUCT_ID,PRODUCT_NAME,BRAND_ID,COLOR_ID,SIZE_ID,CATEGORY_ID,PRODUCT_PRICE) VALUES(104,'long coat',100004,1004,104,104,55)
    INTO COMM_PRODUCT(PRODUCT_ID,PRODUCT_NAME,BRAND_ID,COLOR_ID,SIZE_ID,CATEGORY_ID,PRODUCT_PRICE) VALUES(105,'pants',100005,1005,105,105,19)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COMM_SHIPPING(SHIPPING_ID,SHIPPED_DATE,CUSTOMER_ID,STATUS) VALUES(1000001,'2024-01-05',1,101)
    INTO COMM_SHIPPING(SHIPPING_ID,SHIPPED_DATE,CUSTOMER_ID,STATUS) VALUES(1000002,'2024-02-05',2,100)
    INTO COMM_SHIPPING(SHIPPING_ID,SHIPPED_DATE,CUSTOMER_ID,STATUS) VALUES(1000003,'2024-03-05',3,103)
    INTO COMM_SHIPPING(SHIPPING_ID,SHIPPED_DATE,CUSTOMER_ID,STATUS) VALUES(1000004,'2024-04-05',4,104)
    INTO COMM_SHIPPING(SHIPPING_ID,SHIPPED_DATE,CUSTOMER_ID,STATUS) VALUES(1000005,'2024-05-05',5,105)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COMM_PAYMENT(PAYMENT_ID,CUSTOMER_ID,PAYMENT_DATE,PAYMENT_METHOD,AMOUNT) VALUES(1001,1,'24-JAN-01','credit',200)
    INTO COMM_PAYMENT(PAYMENT_ID,CUSTOMER_ID,PAYMENT_DATE,PAYMENT_METHOD,AMOUNT) VALUES(1002,2,'24-FEB-01','credit',450)
    INTO COMM_PAYMENT(PAYMENT_ID,CUSTOMER_ID,PAYMENT_DATE,PAYMENT_METHOD,AMOUNT) VALUES(1003,3,'24-MAR-01','credit',330)
    INTO COMM_PAYMENT(PAYMENT_ID,CUSTOMER_ID,PAYMENT_DATE,PAYMENT_METHOD,AMOUNT) VALUES(1004,4,'24-APR-01','credit',770)
    INTO COMM_PAYMENT(PAYMENT_ID,CUSTOMER_ID,PAYMENT_DATE,PAYMENT_METHOD,AMOUNT) VALUES(1005,5,'24-MAY-01','credit',590)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COMM_ORDER(ORDER_ID,CUSTOMER_ID,PAYMENT_ID,SHIPPING_ID,ORDER_DATE,TOTAL_PRICE) VALUES(111,1,1001,1000001,'24-JAN-01',200)
    INTO COMM_ORDER(ORDER_ID,CUSTOMER_ID,PAYMENT_ID,SHIPPING_ID,ORDER_DATE,TOTAL_PRICE) VALUES(112,2,1002,1000002,'24-FEB-01',450)
    INTO COMM_ORDER(ORDER_ID,CUSTOMER_ID,PAYMENT_ID,SHIPPING_ID,ORDER_DATE,TOTAL_PRICE) VALUES(113,3,1003,1000003,'24-MAR-01',330)
    INTO COMM_ORDER(ORDER_ID,CUSTOMER_ID,PAYMENT_ID,SHIPPING_ID,ORDER_DATE,TOTAL_PRICE) VALUES(114,4,1004,1000004,'24-APR-01',770)
    INTO COMM_ORDER(ORDER_ID,CUSTOMER_ID,PAYMENT_ID,SHIPPING_ID,ORDER_DATE,TOTAL_PRICE) VALUES(115,5,1005,1000005,'24-MAY-01',590)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COMM_ORDER_ITEM(ORDER_ITEM_ID,QUANTITY,PRICE,PRODUCT_ID,ORDER_ID) VALUES(0001,100,20,101,111)
    INTO COMM_ORDER_ITEM(ORDER_ITEM_ID,QUANTITY,PRICE,PRODUCT_ID,ORDER_ID) VALUES(0002,190,13,102,112)
    INTO COMM_ORDER_ITEM(ORDER_ITEM_ID,QUANTITY,PRICE,PRODUCT_ID,ORDER_ID) VALUES(0003,140,22,103,113)
    INTO COMM_ORDER_ITEM(ORDER_ITEM_ID,QUANTITY,PRICE,PRODUCT_ID,ORDER_ID) VALUES(0004,600,55,104,114)
    INTO COMM_ORDER_ITEM(ORDER_ITEM_ID,QUANTITY,PRICE,PRODUCT_ID,ORDER_ID) VALUES(0005,400,19,105,115)
SELECT 1 FROM DUAL;
    

INSERT ALL
    INTO COMM_SHOPPING_CART(CART_ID,CUSTOMER_ID,PRODUCT_ID,QUANTITY) VALUES(101,1,101,3)
    INTO COMM_SHOPPING_CART(CART_ID,CUSTOMER_ID,PRODUCT_ID,QUANTITY) VALUES(102,2,102,4)
    INTO COMM_SHOPPING_CART(CART_ID,CUSTOMER_ID,PRODUCT_ID,QUANTITY) VALUES(103,3,103,5)
    INTO COMM_SHOPPING_CART(CART_ID,CUSTOMER_ID,PRODUCT_ID,QUANTITY) VALUES(104,4,104,6)
    INTO COMM_SHOPPING_CART(CART_ID,CUSTOMER_ID,PRODUCT_ID,QUANTITY) VALUES(105,5,105,7)
SELECT 1 FROM DUAL;









